kind: ConfigMap
apiVersion: v1
metadata:
  name: wf-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  wf.sh: |
    #!/bin/bash

    # get pod root path
    for dir in $(ls -t ~/{{ .Values.Deployment.namespace }}/)
    do
      if [ -d ~/{{ .Values.Deployment.namespace }}/$dir ]
      then
        # read the pgid file
        export POD_ROOT_PATH=~/{{ .Values.Deployment.namespace }}/$dir
        echo "POD_ROOT_PATH: $POD_ROOT_PATH"
        break
      fi
    done

    # Run ERSAP
    # get the node ip from hostname
    export NODE_NAME=$(hostname | awk -F'-' '{print $2}')
    ## if NODE_NAME is "fs", then set NODE_NUMBER to 7
    if [ "$NODE_NAME" == "fs" ]; then
      export NODE_NUMBER=7
    else
      export NODE_NUMBER=$(echo $NODE_NAME | awk -F'-' '{print $2}')
    fi
    export PR_HOST=129.57.177.$NODE_NUMBER
    export LB_HOST=129.57.177.135
    echo "LB_HOST: $LB_HOST, PR_HOST: $PR_HOST"

    ## pull the docker image
    docker rmi gurjyan/ersap:v0.1
    docker pull gurjyan/ersap:v0.1
    docker run -d --rm --net=host -e "LB_HOST=$LB_HOST" -e "PR_HOST=$PR_HOST" --entrypoint /ersap/run-pipeline-node.sh gurjyan/ersap:v0.1

    ## find the last container id
    export CONTAINER_ID=$(docker ps -l -q)
    ## store containerid for killing the container
    echo $CONTAINER_ID > $POD_ROOT_PATH/containers/wf/containerid


    ## find the pgid of the process in the container with "UseNUMA" in its command
    sleep 10
    export PGID=$(docker top $CONTAINER_ID -eo pid,cmd | grep UseNUMA | awk '{print $1}')
    echo $PGID > $POD_ROOT_PATH/containers/wf/pgid
    echo "PGID: $PGID"

    ## keep process alive
    sleep $1
    ## kill the container
    docker kill $CONTAINER_ID
