apiVersion: v1
kind: Service
metadata:
  name: prometheus-{{ .Values.Deployment.name}}
  namespace: {{ .Values.Prometheus.namespace}}
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: {{ .Values.Deployment.name}}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
