Pod:
  name: ersap-test
  namespace: default

  ersap_settings:
    image: docker:gurjyan/ersap:v0.1
    cmd: /ersap/run-pipeline-node.sh

  prometheus_settings:
    image: jlabtsai/process-exporter:pgid-go
    cmd: -V /proc:/host_proc --entrypoint
    wait_time_before_start: 8
    process_exporter_port: "1776"

Service:
- name:  ersap-exporter
  protocol: TCP
  port: 20059
  targetPort: 20059
  path: /metrics
  interval: 15s
- name: process-exporter
  protocol: TCP
  port: 20060
  targetPort: 20060
  path: /metrics
  interval: 15s
- name: ejfat-exporter
  protocol: TCP
  port: 20061
  targetPort: 20061
  path: /metrics
  interval: 15s
- name: JRM-exporter
  protocol: TCP
  port: 10046
  targetPort: 10046
  path: /metrics/resource
  interval: 15s

PersistentVolume:
  node: jiriaf2302-control-plane
  path: /var/prom
  size: 10Gi
Prometheus:
  serviceaccount: prometheus-k8s
  namespace: monitoring

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md