global:
  scrape_interval: 30s
  scrape_timeout: 20s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vk'
    scheme: https
    static_configs:
      - targets: ['localhost:10250']
    metrics_path: /metrics/resource
    tls_config:
      insecure_skip_verify: true

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['localhost:12345']