global:
  scrape_interval: 30s
  scrape_timeout: 20s  

scrape_configs:
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: 'j-vk1'
    scheme: https
    static_configs:
      - targets: ['localhost:10001']
    metrics_path: /metrics/resource
    tls_config:
      insecure_skip_verify: true

  - job_name: 'j-ersap-process-exporter1'
    static_configs:
      - targets: ['localhost:20001']

  - job_name: 'vd-ersap1'
    static_configs:
    - targets: ['localhost:30001']
  
  - job_name: 'vd-ejfat1'
    static_configs:
    - targets: ['localhost:40001']



  - job_name: 'j-vk2'
    scheme: https
    static_configs:
      - targets: ['localhost:10002']
    metrics_path: /metrics/resource
    tls_config:
      insecure_skip_verify: true

  - job_name: 'j-ersap-process-exporter2'
    static_configs:
      - targets: ['localhost:20002']

  - job_name: 'vd-ersap2'
    static_configs:
    - targets: ['localhost:30002']
  
  - job_name: 'vd-ejfat2'
    static_configs:
    - targets: ['localhost:40002']