kind: ConfigMap
apiVersion: v1
metadata:
  name: wf
  namespace: default
data:
  wf.sh: |
    #!/bin/bash
    shifter --image=docker:gurjyan/ersap:v0.4 --entrypoint
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prom
  namespace: default
data:
  prom.sh: |
    #!/bin/bash
    sleep 10
    ssh -NfR 1234:localhost:2221 $PROM_SERVER 
    shifter --image=jlabtsai/process-exporter:pgid -V /proc:/host_proc --entrypoint
    ssh -NfR $PROCESS_EXPORTER_PORT:localhost:$PROCESS_EXPORTER_PORT $PROM_SERVER 

---

apiVersion: v1
kind: Pod
metadata:
  name: ersap
spec:
  containers:
    - name: wf
      image: wf
      command: ["/bin/bash", "-c"]
      args: ["bash $workdrir/wf.sh >> $workdrir/stdout 2>> $workdrir/stderr"]
      env:
        - name: workdrir
          value: ~/run-ersap/ersap/wf

      volumeMounts:
        - name: wf
          mountPath: ~/run-ersap/ersap/wf
        - name: pgid-wf
          mountPath: ~/run-ersap/ersap/wf/pgid

      resources:
        limits:
          cpu: "32"
          memory: 128Gi

    - name: prom
      image: prom
      command: ["/bin/bash", "-c"]
      args: ["bash $workdir/prom.sh >> $workdir/stdout 2>> $workdir/stderr"]
      env:
        - name: workdir
          value: ~/run-ersap/ersap/prom
        - name: PGID_FILE
          value: ~/run-ersap/ersap/wf/pgid/wf.pgid
        - name: PROCESS_EXPORTER_PORT
          value: "1911"
        - name: PROCESS_EXPORTER_CONFIG
          value: ~/run-ersap/ersap/prom/process-exporter.yml
        - name: PROM_SERVER
          value: jeng-yuantsai@72.84.73.170

      volumeMounts:
        - name: prom
          mountPath: ~/run-ersap/ersap/prom
        - name: pgid-prom
          mountPath: ~/run-ersap/ersap/prom/pgid

      resources:
        limits:
          cpu: "32"
          memory: 128Gi


  volumes:
    - name: wf 
      configMap:
        name: wf
    - name: prom
      configMap:
        name: prom
    - name: pgid-wf
      emptyDir: {}
    - name: pgid-prom
      emptyDir: {}
        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"


---
