apiVersion: batch/v1
kind: Job
metadata:
  name: init-directory-{{ .Values.Deployment.name}}
  namespace: {{ .Values.Prometheus.namespace}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      containers:
      - name: init-directory
        image: busybox
        command: ['sh', '-c', 'mkdir -p {{ .Values.PersistentVolume.path}}/{{ .Values.Deployment.name}}']
        volumeMounts:
        - name: scratch-volume
          mountPath: {{ .Values.PersistentVolume.mountPath}}
      volumes:
      - name: scratch-volume
        hostPath:
          path: {{ .Values.PersistentVolume.mountPath}}
          type: DirectoryOrCreate
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.PersistentVolume.node}}
      restartPolicy: Never