kind: ConfigMap
apiVersion: v1
metadata:
  name: wf
  namespace: default
data:
  wf.sh: |
    #!/bin/bash
    sleep $SLEEP
    echo $HOME
    # shifter --image=docker:gurjyan/ersap:v0.4 --entrypoint
    shifter --image=docker:gurjyan/ersap:v0.4 -- /bin/bash /ersap/run-pipeline-4.sh

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prom
  namespace: default
data:
  prom.sh: |
    #!/bin/bash
    sleep $SLEEP

    for i in {2221..2224}
    do
      j=$((i + $PROM_PORT_OFFSET))
      ssh -NfR $j:localhost:$i $PROM_SERVER
    done

    ssh -NfR $PROCESS_EXPORTER_PORT:localhost:$PROCESS_EXPORTER_PORT $PROM_SERVER
    shifter --image=jlabtsai/process-exporter:pgid-go -V /proc:/host_proc --entrypoint


---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kill
  namespace: default
data:
  kill.sh: |
    #!/bin/bash
    sleep $SLEEP
    # logout the shell
    exit