# write a pod to test the volume
apiVersion: v1
kind: Pod
metadata:
#set name as the JOBNAME
  name: e1
spec:
  automountServiceAccountToken: false
  containers:
  - name: test-shell
    image: fake
    command:

      - "echo"
      - "'"
      - "(setsid shifter --image=docker:gurjyan/ersap:v0.4 --entrypoint & echo $! > $HOME/sid.out)"
      # - "&&"
      # - "(ssh -i $HOME/.ssh/nersc -NfR 1234:localhost:2221 x3113c0s17b0n0)"
      # - "&&"
      # - "(export PROCESS_EXPORTER_PORT=1911 && sleep 10 && shifter --image=jlabtsai/process-exporter:v1.0.0 -V /proc:/host_proc --entrypoint &)"
      # - "&&"
      # - "(export PROCESS_EXPORTER_PORT=1911 && export PROM_SERVER=x3113c0s17b0n0 && ssh -i $HOME/.ssh/nersc -NfR $PROCESS_EXPORTER_PORT:localhost:$PROCESS_EXPORTER_PORT $PROM_SERVER)"
      - "' > $HOME/hostpipe/vk-cmd"

    resources:
      limits: 
        cpu: 1 #upper limit
        # memory: 500Mi
      requests:
        cpu: 1 #lower limit
        # memory: 200Mi
 
# dont use control-plane node
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/hostname: vk-swif-nersc
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"

# --- the second ersap pod at the below --- #
# ---