#write me a regular pod config file
# https://kubernetes.io/docs/concepts/workloads/pods/

apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
spec:
  containers:
    - name: myapp
      image: "busybox"

  nodeSelector:
    kubernetes.io/hostname: kind-control-plane
