# write a pod to test the volume
apiVersion: v1
kind: Pod
metadata:
#set name as the JOBNAME
  name: e8
spec:
  containers:
  - name: test-shell
    image: fake
    command:

      - "echo"
      - "'"
      - "(setsid shifter --image=docker:gurjyan/ersap:v0.4 -- /bin/bash /ersap/run-pipeline-8.sh & echo $! > $HOME/sid.out)"
      - "&&"
      - "(ssh -NfR 2221:localhost:2221 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2222:localhost:2222 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2223:localhost:2223 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2224:localhost:2224 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2224:localhost:2225 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2224:localhost:2226 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2224:localhost:2227 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(ssh -NfR 2224:localhost:2228 jeng-yuantsai@72.84.73.170)"
      - "&&"
      - "(export PROCESS_EXPORTER_PORT=1911 && sleep 10 && shifter --image=jlabtsai/process-exporter:v1.0.0 -V /proc:/host_proc --entrypoint &)"
      - "&&"
      - "(export PROCESS_EXPORTER_PORT=1911 && export PROM_SERVER=jeng-yuantsai@72.84.73.170 && ssh -NfR $PROCESS_EXPORTER_PORT:localhost:$PROCESS_EXPORTER_PORT $PROM_SERVER)"

      - "' > $HOME/hostpipe/vk-cmd"

    resources:
      limits: 
        cpu: 1 #upper limit
        # memory: 500Mi
      requests:
        cpu: 1 #lower limit
        # memory: 200Mi
 
# dont use control-plane node
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/hostname: vk-ersap1
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"

# --- the second ersap pod at the below --- #
# ---