# write a pod to test the volume
apiVersion: v1
kind: Pod
metadata:
#set name as the JOBNAME
  name: job
spec:
  containers:
  - name: test-shell
    image: fake
    command:

      - "echo"
      - "'"
      - "(setsid shifter --image=docker:gurjyan/ersap:v0.1 --entrypoint& echo $! > $HOME/sid.out)"
      - "&&"
      - "(export PROCESS_EXPORTER_PORT=1895 && sleep 10 && shifter --image=jlabtsai/process-exporter:v1.0.0 -V /proc:/host_proc --entrypoint &)"
      - "&&"
      - "(export PROCESS_EXPORTER_PORT=1895 && export PROM_SERVER=jeng-yuantsai@72.84.73.170 && ssh -NfR $PROCESS_EXPORTER_PORT:localhost:$PROCESS_EXPORTER_PORT $PROM_SERVER)"
      - "' > $HOME/hostpipe/vk-cmd"

    resources:
      limits: 
        cpu: 1 #upper limit
        # memory: 500Mi
      requests:
        cpu: 1 #lower limit
        # memory: 200Mi
 
# dont use control-plane node
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"