kind: ConfigMap
apiVersion: v1
metadata:
  name: docker-stop
data:
  docker-stop.sh: |
    #!/bin/bash

    # get contianer id from the file cont_id_file
    export POD_DIR=~/$ns/$pod_name

    ## look for all cont_id_files in the directory $POD_DIR/containers/
    export CONTAINER_ID=$(cat $POD_DIR/containers/*/cont_id)

    ## look for all pgid files in the directory $POD_DIR/containers/
    export PGID_FILE=$(ls $POD_DIR/containers/*/pgid)

    # kill the container by docker stop if container is still running
    ## find running containers
    export RUNNING_CONTAINERS=$(docker ps -q)
    ## kill the container if it is running
    if [[ $RUNNING_CONTAINERS == *$CONTAINER_ID* ]]; then
      docker stop $CONTAINER_ID
    fi

    # kill the processes by pgid
    for PGID_FILE in $PGID_FILES
    do
      export PGID=$(cat $PGID_FILE)
      pkill -g $PGID
    done

---

apiVersion: v1
kind: Pod
metadata:
  name: kill # Job Name Here
spec:
  containers:
    - name: c1
      image: docker-stop
      command: ["bash"]
      args: [""] # Time and cpu should go here
      env:
        - name: ns
          value: "default"
        - name: pod_name
          value: "ersap"
      volumeMounts:
        - name: docker-stop
          mountPath: docker-stop        
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1" # Number of CPUs Here as well
          memory: 1Gi # Memory Here 
  volumes:
    - name: docker-stop
      configMap:
        name: docker-stop
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/hostname: vk-ejfat
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"
  restartPolicy: Never