apiVersion: v1
kind: Pod
metadata:
  name: ersap
  labels:
    app: ersap
  namespace: 100g
spec:
  containers:
    - name: wf
      image: wf
      command: ["bash"]
      args: [""]
      volumeMounts:
        - name: wf
          mountPath: wf
      resources:
        limits:
          cpu: "256"
        requests:
          cpu: "256"

    - name: prom
      image: prom
      command: ["bash"]
      args: [""]
      env:
        - name: PGID_FILE
          value: ~/100g/ersap/containers/wf/pgid
        - name: ERSAP_PORT
          value: "12221"
        - name: EJFAT_PORT
          value: "18080"
        - name: PROCESS_EXPORTER_PORT
          value: "11776"

      volumeMounts:
        - name: prom
          mountPath: prom
      # resources:
      #   limits:
      #     cpu: "32"
      #     memory: 128Gi

  volumes:
    - name: wf
      configMap:
        name: wf
    - name: prom
      configMap:
        name: prom
        
  nodeSelector:
    kubernetes.io/role: agent
    # kubernetes.io/hostname: vk-nersc1
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"
