Deployment:
  name: <project-id>
  namespace: default

PersistentVolume:
  node: jiriaf2302-control-plane
  mountPath: /data
  path: /data/prom
  size: 10Gi
  
Prometheus:
  serviceaccount: prometheus-k8s
  namespace: monitoring

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md