Deployment:
  name: <project-id>
  namespace: default

PersistentVolume:
  node: jiriaf2301-control-plane
  mountPath: /scratch
  path: /scratch/prom
  size: 10Gi
  
Prometheus:
  serviceaccount: prometheus-k8s
  namespace: monitoring

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md