Deployment:
  name: this-name-is-changing
  namespace: default
  replicas: 1
  serviceMonitorLabel: ersap-test4 # this is the label for the serviceMonitor. It can be the same for multiple deployments if using a single prometheus instance.
  site: perlmutter #ornl

Service:
- name:  ersap-exporter
  protocol: TCP
  port:  20000
  originalPort: 2221
  path: /metrics
  interval: 15s
- name: process-exporter
  protocol: TCP
  port: 20001
  originalPort: 1776
  path: /metrics
  interval: 15s
- name: ejfat-exporter
  protocol: TCP
  port: 20002
  originalPort: 8088
  path: /metrics
  interval: 15s
- name: jrm-exporter
  protocol: TCP
  port:  10000
  originalPort: 10000
  path: /metrics/resource
  interval: 15s
- name: ersap-queue
  protocol: TCP
  port:  20003
  originalPort: 2222
  path: /metrics/resource
  interval: 15s


PersistentVolume:
  node: jiriaf2302-control-plane
  path: /var/prom
  size: 5Gi
Prometheus:
  serviceaccount: prometheus-k8s
  namespace: monitoring

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md