kind: ConfigMap
apiVersion: v1
metadata:
  name: wf-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  wf.sh: |
    #!/bin/bash
    # export LB_HOST=$1
    # export PR_HOST=$2
    # apptainer run {{ .Values.Deployment.ersapSettings.image }} -- {{ .Values.Deployment.ersapSettings.cmd }}
    shifter --image={{ .Values.Deployment.ersapSettings.image  }} -- {{ .Values.Deployment.ersapSettings.cmd }}



---

kind: ConfigMap
apiVersion: v1
metadata:
  name: prom-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  prom.sh: |
    #!/bin/bash
    for dir in $(ls -t ~/{{ .Values.Deployment.namespace }}/)
    do
      if [ -d ~/{{ .Values.Deployment.namespace }}/$dir ]
      then
        # read the pgid file
        export PGID_FILE=~/{{ .Values.Deployment.namespace }}/$dir/containers/wf/pgid
        echo "PGID_FILE: $PGID_FILE"
        break
      fi
    done


    export GROUP_FOR_CONFIG={{ "{{.ExeBase}}:{{.Username}}:{{.PID}}" | quote }}
    # export PGID_FILE=/global/homes/j/jlabtsai/pgid
    # export CMDS_FOR_CONFIG="virtual-kubelet"

    sleep 15
    # apptainer run --bind /proc:/host_proc {{ .Values.Deployment.processExporterSettings.image }}
    shifter --image={{ .Values.Deployment.processExporterSettings.image }} -V /proc:/host_proc --entrypoint
