Deployment:
  name: this-name-is-changing
  namespace: default
  replicas: 1
  serviceMonitorLabel: ersap-test4 # this is the label for the serviceMonitor. It can be the same for multiple deployments if using a single prometheus instance.

  cpuUsage: "64"
  ejfatNode: "2"

  ersapSettings:
    image: gurjyan/ersap:v0.1 #jlabtsai/ersap:thread #gurjyan/ersap:v0.1
    cmd: /ersap/run-pipeline.sh
    file: /x.ersap

Service:
- name: jrm-exporter
  protocol: TCP
  port: {{ add 10000 .Values.Deployment.ejfatNode }}
  originalPort: {{ add 10000 .Values.Deployment.ejfatNode }}
  path: /metrics/resource
  interval: 15s
- name:  ersap-exporter
  protocol: TCP
  port: {{ add 20000 .Values.Deployment.ejfatNode }}
  originalPort: 2221
  path: /metrics
  interval: 15s
- name: process-exporter
  protocol: TCP
  port: {{ add 30000 .Values.Deployment.ejfatNode }}
  originalPort: 1776
  path: /metrics
  interval: 15s
- name: ejfat-exporter
  protocol: TCP
  port: {{ add 40000 .Values.Deployment.ejfatNode }}
  originalPort: 8088
  path: /metrics
  interval: 15s
- name: ersap-queue
  protocol: TCP
  port:  {{ add 50000 .Values.Deployment.ejfatNode }}
  originalPort: 2222
  path: /metrics/resource
  interval: 15s



PersistentVolume:
  node: jiriaf2302-control-plane
  path: /var/prom
  size: 5Gi
Prometheus:
  serviceaccount: prometheus-k8s
  namespace: monitoring

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md