apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.Deployment.name}}
  namespace: {{ .Values.Deployment.namespace}}
spec:
  parallelism: {{ .Values.Deployment.replicas}}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.name}}
    spec:
      containers:
      - name: wf
        image: wf
        command: ["bash"]
        args: ["28800"]
        ports:
        - containerPort: {{ index .Values.Service 0 "originalPort" }}
          hostPort: {{ index .Values.Service 0 "port" }}
        - containerPort: {{ index .Values.Service 2 "originalPort" }}
          hostPort: {{ index .Values.Service 2 "port" }}
        - containerPort: {{ index .Values.Service 4 "originalPort" }}
          hostPort: {{ index .Values.Service 4 "port" }}
        volumeMounts:
        - name: wf
          mountPath: wf
        resources:
          limits:
            cpu: {{ if eq .Values.Deployment.site "perlmutter" }}"256"{{ else if eq .Values.Deployment.site "ornl" }}"128"{{ else if contains "fabric" .Values.Deployment.site }}"64"{{ else }}"256"{{ end }}
          requests:
            cpu: {{ if eq .Values.Deployment.site "perlmutter" }}"256"{{ else if eq .Values.Deployment.site "ornl" }}"128"{{ else if contains "fabric" .Values.Deployment.site }}"64"{{ else }}"256"{{ end }}
      - name: prom
        image: prom
        command: ["bash"]
        args: [""]
        env:
          - name: PROCESS_EXPORTER_PORT
            value: "{{ index .Values.Service 1 "originalPort" }}"
        ports:
          - containerPort: {{ index .Values.Service 1 "originalPort" }}
            hostPort: {{ index .Values.Service 1 "port" }}
          - containerPort: {{ index .Values.Service 3 "originalPort" }}
            hostPort: {{ index .Values.Service 3 "port" }}
        volumeMounts:
          - name: prom
            mountPath: prom

      volumes:
      - name: wf
        configMap:
          name: wf-{{ .Values.Deployment.name }}
      - name: prom
        configMap:
          name: prom-{{ .Values.Deployment.name}}
          
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/role: agent
      tolerations:
      - key: "virtual-kubelet.io/provider"
        value: "mock"
        effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: jiriaf.site
                operator: In
                values:
                - {{ .Values.Deployment.site}}
