kind: ConfigMap
apiVersion: v1
metadata:
  name: wf-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  wf.sh: |
    #!/bin/bash
    # export LB_HOST=$1
    # export PR_HOST=$2
    # job-configmap.yaml
    {{- if eq .Values.Deployment.site "perlmutter" }}
        shifter --image=gurjyan/ersap:v0.1 -- /ersap/run-pipeline.sh
    {{- else }}
        export PR_HOST=$(hostname -I | awk '{print $2}')
        apptainer run ~/ersap_v0.1.sif -- /ersap/run-pipeline.sh
    {{- end }}



---

kind: ConfigMap
apiVersion: v1
metadata:
  name: prom-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  prom.sh: |
    #!/bin/bash
    # for dir in $(ls -t ~/{{ .Values.Deployment.namespace }}/)
    # do
    #   if [ -d ~/{{ .Values.Deployment.namespace }}/$dir ]
    #   then
    #     # read the pgid file
    #     export PGID_FILE=~/{{ .Values.Deployment.namespace }}/$dir/containers/wf/pgid
    #     echo "PGID_FILE: $PGID_FILE"
    #     break
    #   fi
    # done


    export GROUP_FOR_CONFIG={{ "{{.ExeBase}}:{{.Username}}:{{.PID}}" | quote }}
    export CMDS_FOR_CONFIG="java"

    sleep 15
    {{- if eq .Values.Deployment.site "perlmutter" }}
        shifter --image=jlabtsai/process-exporter:pgid-go -V /proc:/host_proc --entrypoint
    {{- else }}
        apptainer run --bind /proc:/host_proc ~/process-exporter_pgid-go.sif
    {{- end }}